In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("netflix_data.csv")

# Question 1

In [4]:
def total_cast(data):
    data = str(data)
    if data == "nan":
        return 0
    else:
        return len(data.split(","))
data["num_of_cast"] = data["cast"].apply(total_cast)

In [5]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,num_of_cast
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV,11
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas,6
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies,9
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action,9
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas,12

# Question 2

In [6]:
data.groupby("genre")["type"].value_counts()

genre                 type
Action                Movie       721
Anime Features        Movie        19
Anime Series          TV Show     148
British TV            TV Show     232
Children              Movie       502
Classic               TV Show      21
Classic Movies        Movie        77
Comedies              Movie      1074
Crime TV              TV Show     369
Cult Movies           Movie        12
Documentaries         Movie       751
Docuseries            TV Show     194
Dramas                Movie      1384
Horror Movies         Movie       244
Independent Movies    Movie        20
International Movies  Movie       114
International TV      TV Show     690
Kids                  TV Show     359
LGBTQ Movies          Movie         1
Music                 Movie        17
Reality TV            TV Show     102
Romantic Movies       Movie         3
Romantic TV           TV Show      28
Sci-Fi                Movie        11
Spanish-Language      TV Show       2
Sports Movies         Movie         1
Stand-Up              Movie       321
                      TV Show      33
TV Action             TV Show      37
TV Comedies           TV Show     110
TV Dramas             TV Show      62
TV Horror             TV Show      10
TV Sci                TV Show       1
TV Shows              TV Show      12
Thrillers             Movie        49
Uncategorized         Movie        56
Name: type, dtype: int64